{
    "name": "Operaciones",
    "summary": "LEULIT OPERACIONES",
    "description": "\n    ",
    "author": "Leulit S.L.",
    "website": "http://www.leulit.com",
    "category": "leulit",
    "version": "17.0.1.0.0",
    "depends": [
        "leulit",
        "leulit_parte_145",
        "leulit_tarea"
    ],
    "data": [
        "security.xml",
        "sequences.xml",
        "views/leulit_vuelo.xml",
        "views/leulit_vuelo_taller.xml",
        "views/leulit_operaciones_performance.xml",
        "views/leulit_piloto_adjunto.xml",
        "views/sale_order.xml",
        "views/hr_expense.xml",
        "views/leulit_piloto.xml",
        "views/leulit_ruta.xml",
        "views/leulit_ruta_aerovia.xml",
        "views/leulit_punto.xml",
        "views/leulit_weight_and_balance.xml",
        "views/leulit_hist_weight_and_balance.xml",
        "views/leulit_postvuelo.xml",
        "views/leulit_realizados.xml",
        "views/leulit_tipos_vuelo.xml",
        "views/leulit_operador.xml",
        "views/leulit_helipuerto.xml",
        "views/leulit_vuelo_wizard_report.xml",
        "views/leulit_informe_seguros.xml",
        "views/ptv.xml",
        "views/ficha_vuelo_report.xml",
        "views/ficha_vuelo_report_4_0_1.xml",
        "views/registro_vuelo_aeronaves.xml",
        "views/registro_consumosaeronave_report.xml",
        "views/report_piloto_log_book.xml",
        "views/leulit_performance.xml",
        "views/leulit_helicoptero.xml",
        "views/leulit_freelance_actividad_aerea.xml",
        "views/leulit_wizard_freelance_actividad_aerea.xml",
        "views/report_format_27.xml",
        "menu.xml"
    ],
    "demo": [],
    "css": [],
    'assets': {
        'web.assets_backend': [
            'leulit_operaciones/static/src/js/gmap_aerovia.js',
            'leulit_operaciones/static/src/js/gmap_ruta.js',
            'leulit_operaciones/static/src/js/weight_and_balance.js',
            'leulit_operaciones/static/src/js/performance_constants.js',
            'leulit_operaciones/static/src/js/performance.js',
            'leulit_operaciones/static/src/js/pag_cargada.js',
        ],
    },
    "qweb": [
        "static/src/xml/weight_and_balance.xml",
        "static/src/xml/parte_vuelo_buttons.xml"
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "license": "LGPL-3"
}
