from . import leulit_mecanico
from . import leulit_ata
from . import leulit_certificacion
from . import leulit_certificacion_aeronave
from . import maintenance_equipment
from . import maintenance_request
from . import project_task
from . import maintenance_planned_activity
from . import maintenance_plan
from . import leulit_wizard_create_maintenance_request
from . import leulit_wizard_add_task_request
from . import leulit_wizard_ad_task_to_wo
from . import leulit_maintenance_task_preventive
from . import maintenance_stage
from . import leulit_maintenance_crs
from . import leulit_maintenance_boroscopia
from . import leulit_limitaciones_aeronavegabilidad
from . import leulit_maintenance_manual
from . import leulit_maintenance_manual_check
from . import leulit_categoria_manual
from . import res_partner
from . import leulit_job_card
from . import leulit_job_card_item
from . import leulit_maintenance_form_one
from . import leulit_maintenance_form_one_template
from . import leulit_rel_formone_lot
from . import product_product
from . import stock_lot
from . import leulit_tarea_sensible_seguridad
from . import leulit_checklist_tareas_sensibles_seguridad
from . import leulit_service_bulletin
from . import leulit_airworthiness_directive
from . import leulit_wizard_copy_plan
from . import leulit_maintenance_security_inspect
from . import leulit_maintenance_double_check
from . import leulit_modifications_and_repairs
from . import leulit_control_th
from . import leulit_helicoptero
from . import leulit_analisis_aceite
from . import leulit_ficha_datos_seguridad
from . import leulit_helicoptero_pieza
from . import leulit_vuelo