{
    "name": "Leulit",
    "summary": "Leulit - Base",
    "description": "\n    ",
    "author": "Leulit S.L.",
    "website": "http://www.leulit.com",
    "category": "leulit",
    "version": "17.0.1.0.0",
    "depends": [
        "base",
        "mail",
        "hr",
        "purchase",
        "stock",
        "sale_management",
        "hr_expense",
        "website",
        "web",
        "repair",
        "project",
        "hr_timesheet",
        "website_slides",
        "mrp",
        "maintenance",
        "survey",
        "mass_mailing",
        "fleet"
    ],
    "data": [
        "groups.xml",
        "security.xml",
        "paperformats.xml",
        "views/res_config_settings.xml",
        "views/res_partner.xml",
        "views/hr_expense_sheet.xml",
        "views/webclient_templates.xml",
        "views/res_company.xml",
        "views/project_project_views.xml",
        "views/leulit_circular.xml",
        "views/err_import.xml",
        "views/stock.xml",
        "views/sale_order.xml",
        "views/leulit_checklist.xml",
        "views/leulit_report_checklist.xml",
        "views/leulit_checklist_template.xml",
        "views/leulit_checklist_item.xml",
        "adjuntos.xml",
        "menu.xml",
        "precision.xml"
    ],
    'assets': {
        'web.assets_backend': [
            'leulit/static/src/js/widget_semaforo_field.js',
            'leulit/static/src/js/widget_semaforo_cell.js',
            'leulit/static/src/js/widget_keyboardDisabled.js',
        ],
    },
    "demo": [],
    "css": [],
    "installable": True,
    "auto_install": False,
    "application": True,
    "license": "LGPL-3"
}
