{
    "name": "Taller",
    "summary": "LEULIT TALLER",
    "description": "\n    ",
    "author": "Leulit S.L.",
    "website": "http://www.leulit.com",
    "category": "leulit",
    "version": "17.0.1.0.0",
    "depends": [
        "leulit",
        "sale_management",
        "leulit_operaciones",
        "leulit_tarea",
        "hr_maintenance",
        "maintenance_plan",
        "maintenance_equipment_sequence",
        "maintenance_project",
        "maintenance_equipment_hierarchy",
        "maintenance_timesheet"
    ],
    "data": [
        "security.xml",
        "views/leulit_analisis_aceite.xml",
        "views/leulit_ficha_datos_seguridad.xml",
        "views/leulit_control_th.xml",
        "views/leulit_helicoptero.xml",
        "views/leulit_mecanico.xml",
        "views/maintenance_equipment.xml",
        "views/maintenance_request.xml",
        "views/project_task.xml",
        "views/maintenance_planned_activity.xml",
        "views/maintenance_plan.xml",
        "views/leulit_wizard_create_maintenance_request.xml",
        "views/leulit_wizard_add_task_request.xml",
        "views/leulit_wizard_ad_task_to_wo.xml",
        "views/leulit_maintenance_task_preventive.xml",
        "views/maintenance_stage.xml",
        "views/leulit_limitaciones_aeronavegabilidad.xml",
        "views/leulit_maintenance_crs.xml",
        "views/leulit_maintenance_boroscopia.xml",
        "views/leulit_categoria_manual.xml",
        "views/leulit_maintenance_manual.xml",
        "views/leulit_job_card_item.xml",
        "views/leulit_job_card.xml",
        "views/leulit_maintenance_form_one.xml",
        "views/leulit_maintenance_form_one_template.xml",
        "views/leulit_rel_formone_lot.xml",
        "views/leulit_informe_inspeccion_seguridad.xml",
        "views/leulit_informe_doble_check.xml",
        "views/leulit_informe_defectos.xml",
        "views/leulit_informe_tareas_sensibles_seguridad.xml",
        "views/leulit_informe_log_cards_inspection.xml",
        "views/leulit_informe_material_utilizado.xml",
        "views/leulit_checklist_tareas_sensibles_seguridad.xml",
        "views/product_product.xml",
        "views/stock_lot.xml",
        "views/leulit_ata.xml",
        "views/leulit_certificacion.xml",
        "views/leulit_certificacion_aeronave.xml",
        "views/leulit_service_bulletin.xml",
        "views/leulit_airworthiness_directive.xml",
        "views/leulit_wizard_copy_plan.xml",
        "views/leulit_modifications_and_repairs.xml",
        "menu.xml"
    ],
    "demo": [],
    "css": [],
    "installable": True,
    "auto_install": False,
    "application": True,
    "license": "LGPL-3"
}
