from . import leulit_vuelo
from . import leulit_vuelo_tipo_line
from . import leulit_tipos_vuelo
from . import leulit_vuelo_scripts
from . import leulit_operaciones_performance
from . import ir_attachment
from . import leulit_piloto_adjunto
from . import sale_order
from . import hr_expense
from . import leulit_freelance_actividad_aerea
from . import leulit_wizard_freelance_actividad_aerea
from . import res_users
from . import res_partner
from . import leulit_weight_and_balance
from . import leulit_hist_weight_and_balance
from . import leulit_ruta
from . import leulit_rel_ruta_aerovia
from . import leulit_ruta_aerovia
from . import leulit_punto
from . import leulit_rel_planoperacional_aerovia
from . import leulit_piloto
from . import leulit_performance
from . import leulit_operador
from . import leulit_helipuerto
from . import leulit_helicoptero
from . import leulit_16_bravo
from . import leulit_informe_seguros
from . import leulit_vuelo_wizard_report
from . import technical_log_report
